### ISSUE TITLE
Failed to activate the linter-po-util package

### ISSUE THREAD

**Issue by markuskreitzer** [nrobinson2000/linter-po#1]
[Enter steps to reproduce:]

1. Installed on a brand new Mac OS X Installation.
2. Error occurs right after install.

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Mac OS X 10.13.5
**Thrown From**: [linter-po-util](https://github.com/nrobinson2000/linter-po-util) package 1.4.0

### Stack Trace

Failed to activate the linter-po-util package

```
At Cannot read property 'metadata' of undefined

TypeError: Cannot read property 'metadata' of undefined
    at Object.install (/packages/linter-po-util/node_modules/atom-package-deps/lib/main.js:12:66)
    at Object.activate (/packages/linter-po-util/lib/main.js:152:34)
    at Package.activateNow (/Users/markuskreitzer/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Users/markuskreitzer/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Users/markuskreitzer/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Users/markuskreitzer/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Users/markuskreitzer/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Users/markuskreitzer/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Users/markuskreitzer/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Users/markuskreitzer/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Users/markuskreitzer/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Users/markuskreitzer/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Users/markuskreitzer/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

### Commands

```
     -0:32.7.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:32.7.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
build 0.70.0 
busy-signal 1.4.3 
console-panel 0.3.0 
linter-po-util 1.4.0 
particle-dev 0.2.2 
particle-dev-profiles 0.2.3 
tool-bar 1.1.7 
vim-mode-plus 1.34.0 
```

**Comment by nrobinson2000** [comment]
This package is non-functional at the moment. You can modify an existing linter-gcc installation to get the functionality. I’ll post the necesary modifications soon.

**Comment by markuskreitzer** [comment]
Thanks Nathan! You are the best!

**Comment by nrobinson2000** [comment]
If you run https://github.com/nrobinson2000/linter-po-util/blob/master/get-linter-po.sh it should install and modify linter-gcc to provide the functionality. You may need to restart atom.

You will have to create a `.linter-po.json` in the root of each project directory you want to use the linter in.

Example: (to use linter to compile for photon)

```
{
  "platform": "photon"
}
```

You will need to have po-util installed of course. I also recommend that you use `po setup-atom` to install the packages that provide the atom shortcuts for po-util that are a good backup if the linter fails.
